### ISSUE TITLE
RangerForestRegressor not using all CPU cores

### ISSUE THREAD

**Issue by mzagar** [crflynn/skranger#103]
Hi,

I cannot get RangerForestRegressor to use all CPU cores on `Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` with 12 cores.

I expected all cpu cores to be used out of the box, but under htop I see only 1 cpu at 100%.
On htop I can see initially it starts using all the cores but then it ends up using just 1 core on 100%.

When n_jobs=11 and n_estimators=1000 scripts takes a long time to finish (minutes).
When n_jobs=11 and n_estimators=11 then script runs fast (2 seconds).

Am I doing something wrong? 
- Is it expected that only 1 core is used and not all 11 cores as specified in n_jobs?
- am I using n_jobs and n_estimators parameters wrong?

Here is my test script:

```python
from time import time
from sklearn.datasets import load_boston
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from skranger.ensemble import RangerForestRegressor

X, y = fetch_california_housing(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y)

rfr = RangerForestRegressor(n_jobs=11, n_estimators=1000)
start = time()
rfr.fit(X_train, y_train)
end = time()
result = end - start
print('duration: %.3f seconds' % (result))

predictions = rfr.predict(X_test)
print(predictions)

# enable quantile regression on instantiation
rfr = RangerForestRegressor(quantiles=True, n_jobs=11, n_estimators=1000)
start = time()
rfr.fit(X_train, y_train)
end = time()
result = end - start
print('duration: %.3f seconds' % (result))

quantile_lower = rfr.predict_quantiles(X_test, quantiles=[0.1])
print(quantile_lower)

quantile_upper = rfr.predict_quantiles(X_test, quantiles=[0.9])
print(quantile_upper)
```

**Comment by crflynn** [comment]
Thank you for the helpful code sample.

The ranger (C++) part of this execution is actually still very fast. Recently I added more code to facilitate decision tree estimators and a lower-level tree interface. These operations are in python, expensive, and not parallelized which is why you see the core usage drop to 1.

For now you can either downgrade to 0.4.X or comment out some code here locally: https://github.com/crflynn/skranger/blob/211b8babe4aa474cfd4c41166b105c77440104cd/skranger/ensemble/regressor.py#L282-L284

In the meantime I will look at making these operations optional and/or parallelizing them to make them faster.

**Comment by mzagar** [comment]
@crflynn using 0.4.1 did the trick, now I can see all cores being used, thank you.

**Comment by crflynn** [comment]
I made these extra calculations optional in 0.6.0. Should be back to being as fast as 0.4.X by default.
