### ISSUE TITLE
'predict_quantiles' taking too longer than 'predict' in RangerForestRegressor

### ISSUE THREAD

**Issue by kpunyakoti** [crflynn/skranger#105]
skranger RangerForestRegressor's _**predict_quantiles**_ method is taking almost 6-8times longer than regular _**predict**_ method. Is there a way to improve the response time for this?

Also, the below documentation says that **_predict_** method also accepts quantiles parameter, however it is giving me error when I pass quantiles to this method.

https://skranger.readthedocs.io/en/stable/ranger_forest_regressor.html

Could you please let us know which is a better way to predict median values (.5 quantile) with faster response times?

I am using 0.4.1 version (for using all cores)

Thanks

**Comment by crflynn** [comment]
I did some testing locally and it looks like the bulk of the operation is when `np.nanquantile` is called, presumably because it is checking every value for nan. A lot of the code is ported from R, but calling `nanquantile` might not be necessary here. If we call `np.quantile` instead the operation is much faster since those checks are omitted, although not as defensive. We might be able to do that instead; I will take a closer look to see if `nanquantile` is necessary.

>Also, the below documentation says that predict method also accepts quantiles parameter, however it is giving me error when I pass quantiles to this method.

>I am using 0.4.1 version (for using all cores)

The `latest` documentation currently refers to 0.5.0. That functionality is not available in 0.4.X. It wouldn't affect performance since it just calls into the same function anyway.

**Comment by kpunyakoti** [comment]
thanks so much! looking forward to a faster ranger quantile predictions
I found this, a way to make nanquantile faster.
https://gist.github.com/joelrich/9d6472bcb93d553837553fb029328c6e

**Comment by crflynn** [comment]
fixed in 0.6.0
